<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="14096" started-at="2017-12-23T18:43:57Z" finished-at="2017-12-23T18:44:12Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="14096" started-at="2017-12-23T18:43:57Z" finished-at="2017-12-23T18:44:12Z">
      <class name="com.IBM.eStrategy.loginPage.TC001_Login_Invalid_Creds">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.IBM.eStrategy.loginPage.TC001_Login_Invalid_Creds@e25b2fe]" name="setUp" is-config="true" duration-ms="11777" started-at="2017-12-24T00:13:57Z" finished-at="2017-12-24T00:14:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginToApplication(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.IBM.eStrategy.loginPage.TC001_Login_Invalid_Creds@e25b2fe]" name="loginToApplication" duration-ms="0" started-at="2017-12-24T00:14:09Z" data-provider="loginData" finished-at="2017-12-24T00:14:09Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:426)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApplication -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.IBM.eStrategy.loginPage.TC001_Login_Invalid_Creds@e25b2fe]" name="closeBrowser" is-config="true" duration-ms="2212" started-at="2017-12-24T00:14:09Z" finished-at="2017-12-24T00:14:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.IBM.eStrategy.loginPage.TC001_Login_Invalid_Creds -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
